-- Standardize kho_lo_hap schema for FEFO flow
-- Safe to run multiple times.

begin;

create table if not exists public.kho_lo_hap (
  id bigint generated by default as identity primary key,
  "TEN_DUNG_CU" text,
  "NGAY_HAP" text,
  "NGAY_HAP_DATE" date,
  "SO_LUONG" integer not null default 0,
  "HAN_DUNG" text,
  "HAN_DUNG_DATE" date,
  "TRANG_THAI" text not null default 'ready',
  created_at timestamptz not null default now()
);

alter table public.kho_lo_hap add column if not exists "TEN_DUNG_CU" text;
alter table public.kho_lo_hap add column if not exists "NGAY_HAP" text;
alter table public.kho_lo_hap add column if not exists "NGAY_HAP_DATE" date;
alter table public.kho_lo_hap add column if not exists "SO_LUONG" integer default 0;
alter table public.kho_lo_hap add column if not exists "HAN_DUNG" text;
alter table public.kho_lo_hap add column if not exists "HAN_DUNG_DATE" date;
alter table public.kho_lo_hap add column if not exists "TRANG_THAI" text default 'ready';
alter table public.kho_lo_hap add column if not exists created_at timestamptz default now();

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'kho_lo_hap' and column_name = 'ten_dung_cu'
  ) then
    execute 'update public.kho_lo_hap set "TEN_DUNG_CU" = coalesce("TEN_DUNG_CU", ten_dung_cu) where "TEN_DUNG_CU" is null';
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'kho_lo_hap' and column_name = 'ngay_hap'
  ) then
    execute 'update public.kho_lo_hap set "NGAY_HAP" = coalesce("NGAY_HAP", ngay_hap) where "NGAY_HAP" is null';
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'kho_lo_hap' and column_name = 'ngay_hap_date'
  ) then
    execute 'update public.kho_lo_hap set "NGAY_HAP_DATE" = coalesce("NGAY_HAP_DATE", ngay_hap_date) where "NGAY_HAP_DATE" is null';
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'kho_lo_hap' and column_name = 'so_luong'
  ) then
    execute 'update public.kho_lo_hap set "SO_LUONG" = coalesce("SO_LUONG", so_luong)';
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'kho_lo_hap' and column_name = 'han_dung'
  ) then
    execute 'update public.kho_lo_hap set "HAN_DUNG" = coalesce("HAN_DUNG", han_dung) where "HAN_DUNG" is null';
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'kho_lo_hap' and column_name = 'han_dung_date'
  ) then
    execute 'update public.kho_lo_hap set "HAN_DUNG_DATE" = coalesce("HAN_DUNG_DATE", han_dung_date) where "HAN_DUNG_DATE" is null';
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'kho_lo_hap' and column_name = 'trang_thai'
  ) then
    execute 'update public.kho_lo_hap set "TRANG_THAI" = coalesce("TRANG_THAI", trang_thai) where "TRANG_THAI" is null';
  end if;
end $$;

update public.kho_lo_hap
set "SO_LUONG" = coalesce("SO_LUONG", 0),
    "TRANG_THAI" = coalesce(nullif("TRANG_THAI", ''), 'ready'),
    created_at = coalesce(created_at, now());

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'kho_lo_hap_so_luong_non_negative'
  ) then
    alter table public.kho_lo_hap
      add constraint kho_lo_hap_so_luong_non_negative check ("SO_LUONG" >= 0);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'kho_lo_hap_trang_thai_valid'
  ) then
    alter table public.kho_lo_hap
      add constraint kho_lo_hap_trang_thai_valid check ("TRANG_THAI" in ('ready', 'used'));
  end if;
end $$;

create index if not exists idx_kho_lo_hap_fefo
  on public.kho_lo_hap ("TRANG_THAI", "TEN_DUNG_CU", "HAN_DUNG_DATE", id);

create index if not exists idx_kho_lo_hap_ready_qty
  on public.kho_lo_hap ("TEN_DUNG_CU", "HAN_DUNG_DATE")
  where "TRANG_THAI" = 'ready' and "SO_LUONG" > 0;

alter table public.kho_lo_hap disable row level security;
grant select, insert, update, delete on table public.kho_lo_hap to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

commit;
